using System;
using System.IO;
using System.Linq;
using UnityEditor;
using UnityEditor.Animations;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.Rendering;
using Object = UnityEngine.Object;

namespace TsilaRun.Editor
{
    // Prepared FBXs are generated by Tools/prepare_meshy.py from untouched GLB originals.
    public static class MeshyPackIntegration
    {
        public const string Root = "Assets/TsilaRun/Art/Meshy";
        public const string Source = Root + "/Source";
        public const string Generated = Root + "/Generated";
        static readonly string[] Characters = { "Tsila", "Officer" };
        static readonly string[] Props =
        {
            "RoadSection", "Curb", "Tower", "Overhead", "Coin", "CoinMagnet", "Tree", "Palm", "House", "Building",
            "AsiaBuildings", "BaileyBridge", "SandFootprints", "Cliffs", "DirtyTunnel", "JungleHouse", "StreetLamp",
            "SidewalkCurbKit", "ModularTunnel", "OakTree", "RoadSectionAlt", "Rock", "RockTerrain", "SafetyRail",
            "SpeedBoost", "Barrier", "TropicalTreePack", "TropicalHouse"
        };
        public static string PrefabPath(string name) => Generated + "/" + name + ".prefab";

        [MenuItem("Tools/Tsila Run/Apply Meshy Art Pack")]
        public static void ApplyMenu()
        {
            if (EditorApplication.isPlayingOrWillChangePlaymode) return;
            if (!EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo()) return;
            ApplyBatch();
        }

        public static void ApplyAndCapture()
        {
            ApplyBatch();
            PrototypeScreenshots.CaptureBatch();
        }

        public static void ApplyBatch()
        {
            string backup = "Logs/MeshyBackup-" + DateTime.Now.ToString("yyyyMMdd-HHmmss");
            Directory.CreateDirectory(backup);
            foreach (string path in Directory.GetFiles(MobilePrototypeBuilder.Root + "/Prefabs"))
                File.Copy(path, backup + "/" + Path.GetFileName(path), true);
            File.Copy(MobilePrototypeBuilder.ScenePath, backup + "/TsilaRun.unity");
            Directory.CreateDirectory(Generated + "/Materials");
            AssetDatabase.Refresh(ImportAssetOptions.ForceSynchronousImport);
            foreach (string path in Directory.GetFiles(Source + "/Textures", "*.png"))
            {
                var importer = (TextureImporter)AssetImporter.GetAtPath(path.Replace('\\', '/'));
                bool normal = path.Contains("_Normal");
                importer.textureType = normal ? TextureImporterType.NormalMap : TextureImporterType.Default;
                importer.sRGBTexture = !normal;
                importer.mipmapEnabled = true;
                importer.maxTextureSize = path.Contains("BaseColor") && (path.Contains("Tsila_") || path.Contains("Officer_")) ? 2048 : 1024;
                importer.textureCompression = TextureImporterCompression.Compressed;
                importer.wrapMode = TextureWrapMode.Repeat;
                importer.SaveAndReimport();
            }
            foreach (string name in Characters)
            {
                ConfigureModel(name, true);
                ConfigureModel(name + "_LOD1", true);
                BuildCharacter(name);
            }
            foreach (string name in Props)
            {
                ConfigureModel(name, false);
                BuildProp(name);
            }
            PatchPrefabs();
            PatchScene();
            AssetDatabase.SaveAssets();
            ValidateAssets();
            Debug.Log("TSILA_MESHY_INTEGRATION_OK backup=" + backup);
        }

        static void ConfigureModel(string name, bool character)
        {
            string path = Source + "/" + name + ".fbx";
            var importer = (ModelImporter)AssetImporter.GetAtPath(path);
            if (importer == null) throw new InvalidDataException("Missing prepared FBX: " + path);
            importer.globalScale = 1;
            importer.useFileUnits = true;
            importer.importCameras = false;
            importer.importLights = false;
            importer.isReadable = true;
            importer.importNormals = ModelImporterNormals.Import;
            importer.importTangents = ModelImporterTangents.CalculateMikk;
            importer.materialImportMode = ModelImporterMaterialImportMode.ImportStandard;
            importer.animationType = character ? ModelImporterAnimationType.Generic : ModelImporterAnimationType.None;
            importer.avatarSetup = character ? ModelImporterAvatarSetup.CreateFromThisModel : ModelImporterAvatarSetup.NoAvatar;
            importer.optimizeGameObjects = false;
            importer.importAnimation = character && !name.EndsWith("_LOD1");
            importer.animationCompression = ModelImporterAnimationCompression.Off;
            if (importer.importAnimation) importer.clipAnimations = Array.Empty<ModelImporterClipAnimation>();
            importer.SaveAndReimport();
            if (importer.importAnimation)
            {
                var clips = importer.defaultClipAnimations;
                foreach (var clip in clips)
                {
                    string state = new[] { "Idle", "Run", "Jump", "Slide" }.FirstOrDefault(s => clip.name.EndsWith(s, StringComparison.OrdinalIgnoreCase));
                    if (state == null) throw new InvalidDataException("Unexpected Meshy clip: " + clip.name);
                    clip.name = state;
                    clip.loopTime = state == "Idle" || state == "Run";
                    clip.lockRootRotation = true;
                    clip.lockRootHeightY = true;
                    clip.lockRootPositionXZ = true;
                    clip.keepOriginalPositionY = true;
                    clip.keepOriginalPositionXZ = true;
                    clip.keepOriginalOrientation = true;
                }
                importer.clipAnimations = clips;
                importer.SaveAndReimport();
            }
            var model = AssetDatabase.LoadAssetAtPath<GameObject>(path);
            string assetName = name.Replace("_LOD1", "");
            foreach (var source in model.GetComponentsInChildren<Renderer>(true).SelectMany(r => r.sharedMaterials).Distinct())
            {
                if (source == null) throw new InvalidDataException("Missing material: " + name);
                string key = assetName + (character ? source.name.Contains("Body") ? "_Body" : "_FaceDetails" : "_Material");
                string matPath = Generated + "/Materials/" + key + ".mat";
                var shader = Shader.Find("Universal Render Pipeline/Lit");
                var mat = AssetDatabase.LoadAssetAtPath<Material>(matPath);
                if (mat == null) { mat = new Material(shader); AssetDatabase.CreateAsset(mat, matPath); }
                mat.shader = shader;
                mat.SetColor("_BaseColor", Color.white);
                mat.SetTexture("_BaseMap", AssetDatabase.LoadAssetAtPath<Texture2D>(Source + "/Textures/" + assetName + "_BaseColor.png"));
                var normal = AssetDatabase.LoadAssetAtPath<Texture2D>(Source + "/Textures/" + assetName + "_Normal.png");
                mat.SetTexture("_BumpMap", normal);
                // Use the mesh normals for the mobile material; keep baked maps available for later tuning.
                mat.DisableKeyword("_NORMALMAP");
                mat.SetFloat("_Smoothness", .12f);
                mat.SetFloat("_Cull", assetName == "Tree" || assetName == "Palm" ? 0f : 2f);
                mat.SetFloat("_Metallic", assetName == "Coin" ? .45f : 0f);
                if (assetName == "SandFootprints")
                {
                    mat.SetFloat("_Surface", 1f);
                    mat.SetFloat("_Blend", 0f);
                    mat.SetFloat("_SrcBlend", (float)BlendMode.SrcAlpha);
                    mat.SetFloat("_DstBlend", (float)BlendMode.OneMinusSrcAlpha);
                    mat.SetFloat("_ZWrite", 0f);
                    mat.SetOverrideTag("RenderType", "Transparent");
                    mat.EnableKeyword("_SURFACE_TYPE_TRANSPARENT");
                    mat.renderQueue = (int)RenderQueue.Transparent;
                }
                mat.enableInstancing = true;
                EditorUtility.SetDirty(mat);
                importer.AddRemap(new AssetImporter.SourceAssetIdentifier(typeof(Material), source.name), mat);
            }
            importer.SaveAndReimport();
        }

        static GameObject InstantiateModel(string name)
        {
            var model = Object.Instantiate(AssetDatabase.LoadAssetAtPath<GameObject>(Source + "/" + name + ".fbx"));
            model.name = name;
            foreach (var renderer in model.GetComponentsInChildren<Renderer>(true))
            {
                renderer.shadowCastingMode = ShadowCastingMode.Off;
                renderer.receiveShadows = false;
                renderer.lightProbeUsage = LightProbeUsage.Off;
                renderer.reflectionProbeUsage = ReflectionProbeUsage.Off;
            }
            return model;
        }

        static void BuildCharacter(string name)
        {
            var model = InstantiateModel(name);
            var low = InstantiateModel(name + "_LOD1");
            try
            {
                var animator = model.GetComponent<Animator>();
                if (animator == null || animator.avatar == null || !animator.avatar.isValid)
                    throw new InvalidDataException("Invalid character skeleton: " + name);
                string path = Generated + "/" + name + ".controller";
                var controller = AssetDatabase.LoadAssetAtPath<AnimatorController>(path);
                if (controller == null) controller = AnimatorController.CreateAnimatorControllerAtPath(path);
                var machine = controller.layers[0].stateMachine;
                foreach (var state in machine.states) machine.RemoveState(state.state);
                var imported = AssetDatabase.LoadAllAssetsAtPath(Source + "/" + name + ".fbx").OfType<AnimationClip>().Where(c => !c.name.StartsWith("__")).ToArray();
                foreach (string state in new[] { "Idle", "Run", "Jump", "Slide" })
                {
                    var clip = Object.Instantiate(imported.Single(c => c.name == state));
                    clip.name = name + "_" + state;
                    string clipPath = Generated + "/" + clip.name + ".anim";
                    var saved = AssetDatabase.LoadAssetAtPath<AnimationClip>(clipPath);
                    if (saved == null) { AssetDatabase.CreateAsset(clip, clipPath); saved = clip; }
                    else { EditorUtility.CopySerialized(clip, saved); Object.DestroyImmediate(clip); EditorUtility.SetDirty(saved); }
                    var entry = machine.AddState(state); entry.motion = saved;
                    if (state == "Idle") machine.defaultState = entry;
                }
                EditorUtility.SetDirty(controller);
                animator.runtimeAnimatorController = controller;
                animator.applyRootMotion = false;
                animator.cullingMode = AnimatorCullingMode.CullUpdateTransforms;
                var highSkin = model.GetComponentInChildren<SkinnedMeshRenderer>();
                var lowSkin = low.GetComponentInChildren<SkinnedMeshRenderer>();
                var bones = model.GetComponentsInChildren<Transform>().ToDictionary(t => t.name);
                lowSkin.bones = lowSkin.bones.Select(b => bones[b.name]).ToArray();
                lowSkin.rootBone = bones[lowSkin.rootBone.name];
                lowSkin.transform.SetParent(model.transform, true);
                lowSkin.name = name + "_GameplayLOD";
                foreach (var skin in new[] { highSkin, lowSkin })
                {
                    skin.quality = SkinQuality.Bone4;
                    skin.updateWhenOffscreen = false;
                    skin.localBounds = new Bounds(new Vector3(0f, .9f, 0f), new Vector3(4f, 4f, 5f));
                }
                var group = model.AddComponent<LODGroup>();
                group.SetLODs(new[] { new LOD(.25f, new Renderer[] { highSkin }), new LOD(.008f, new Renderer[] { lowSkin }) });
                group.localReferencePoint = Vector3.up * .9f; group.size = 1.8f;
                PrefabUtility.SaveAsPrefabAsset(model, PrefabPath(name));
            }
            finally { Object.DestroyImmediate(model); Object.DestroyImmediate(low); }
        }

        static void BuildProp(string name)
        {
            var root = new GameObject(name);
            try
            {
                var high = InstantiateModel(name); high.transform.SetParent(root.transform, false);
                var low = InstantiateModel(name + "_LOD1"); low.transform.SetParent(root.transform, false);
                if (name == "Coin" || name == "CoinMagnet")
                {
                    Vector3 offset = Vector3.up * (.9f - BlenderPackIntegration.VisualBounds(high).center.y);
                    high.transform.localPosition = offset;
                    low.transform.localPosition = offset;
                }
                var group = root.AddComponent<LODGroup>();
                group.SetLODs(new[]
                {
                    new LOD(.12f, high.GetComponentsInChildren<Renderer>()),
                    new LOD(.01f, low.GetComponentsInChildren<Renderer>())
                });
                group.RecalculateBounds();
                PrefabUtility.SaveAsPrefabAsset(root, PrefabPath(name));
            }
            finally { Object.DestroyImmediate(root); }
        }

        static void ClearChildren(Transform parent)
        { foreach (Transform child in parent.Cast<Transform>().ToArray()) Object.DestroyImmediate(child.gameObject); }

        static RunnerAvatar ReplacePlayer(RunnerPlayer player)
        {
            ClearChildren(player.visual);
            var avatar = MethodVisualBuilder.Character(player.visual, "Tsila");
            avatar.player = player;
            player.rig = avatar.GetComponent<RunnerCharacterRig>();
            player.animatedSlide = true;
            return avatar;
        }

        static void Place(Transform parent, string asset, Vector3 position, float yaw = 0, Vector3 scale = default)
        {
            var model = MethodVisualBuilder.Model(parent, asset);
            model.name = asset == "RoadSection" ? asset : "Meshy " + asset;
            model.transform.localPosition = position;
            model.transform.localRotation = Quaternion.Euler(0, yaw, 0);
            if (scale.sqrMagnitude > 0f) model.transform.localScale = scale;
        }

        static void ClearScenery(Transform root, string preserve = null)
        {
            foreach (Transform child in root.Cast<Transform>().ToArray())
                if (child.name != preserve) Object.DestroyImmediate(child.gameObject);
        }

        static void PatchRoad(GameObject root)
        {
            var section = root.GetComponent<RunnerRoadSection>();
            foreach (Transform child in root.transform.Cast<Transform>().ToArray())
                if (child.GetComponent<RunnerRoadSection>() == null && !section.scenery.Contains(child.gameObject)) Object.DestroyImmediate(child.gameObject);
            Place(root.transform, "RoadSection", Vector3.zero);
            Place(root.transform, "RoadSectionAlt", new Vector3(0f, -.4f, 0f));
            foreach (int side in new[] { -1, 1 }) Place(root.transform, "Curb", new Vector3(side * 4.1f, -.05f, 0f));
            var island = section.scenery[0].transform;
            ClearScenery(island, "Island");
            foreach (int side in new[] { -1, 1 })
            {
                Place(island, "Palm", new Vector3(side * 6f, 0f, 7f), side * 20f);
                Place(island, "Tree", new Vector3(side * 7f, 0f, -3f));
                Place(island, "House", new Vector3(side * 10f, 0f, 4f), side < 0 ? 90 : -90);
                Place(island, "Building", new Vector3(side * 12f, 0f, -7f), side < 0 ? 90 : -90);
                Place(island, "JungleHouse", new Vector3(side * 14f, 0f, -8f), side < 0 ? 90 : -90, Vector3.one * .7f);
                Place(island, "TropicalHouse", new Vector3(side * 10f, 0f, -9f), side < 0 ? 90 : -90, Vector3.one * .8f);
                Place(island, "TropicalTreePack", new Vector3(side * 15f, 0f, 8f), 0f, Vector3.one * .45f);
                Place(island, "AsiaBuildings", new Vector3(side * 17f, 0f, 0f), 0f, Vector3.one * .35f);
                Place(island, "StreetLamp", new Vector3(side * 5f, 0f, -10f), side < 0 ? 180 : 0, Vector3.one * .8f);
            }
            Place(island, "SandFootprints", new Vector3(0f, -.19f, -5f));

            var mountain = section.scenery[1].transform;
            ClearScenery(mountain);
            Place(mountain, "BaileyBridge", new Vector3(0f, -.42f, 0f));
            Place(mountain, "Cliffs", new Vector3(-17f, -1f, 0f));
            Place(mountain, "Cliffs", new Vector3(17f, -1f, 0f));
            Place(mountain, "RockTerrain", new Vector3(-17f, -2f, 0f));
            Place(mountain, "RockTerrain", new Vector3(17f, -2f, 0f));
            Place(mountain, "OakTree", new Vector3(-20f, 0f, -7f));
            Place(mountain, "OakTree", new Vector3(20f, 0f, 7f), 35f);
            Place(mountain, "Rock", new Vector3(-6f, 0f, -10f));
            Place(mountain, "Rock", new Vector3(6f, 0f, 10f));
            Place(mountain, "SidewalkCurbKit", new Vector3(-12f, 0f, 0f), 0f, Vector3.one * .35f);
            Place(mountain, "SidewalkCurbKit", new Vector3(12f, 0f, 0f), 0f, Vector3.one * .35f);
            Place(mountain, "SafetyRail", new Vector3(-4.25f, .65f, -10f), 90f);
            Place(mountain, "SafetyRail", new Vector3(4.25f, .65f, -10f), 90f);
            Place(mountain, "SafetyRail", new Vector3(-4.25f, .65f, -5f), 90f);
            Place(mountain, "SafetyRail", new Vector3(4.25f, .65f, -5f), 90f);
            Place(mountain, "SafetyRail", new Vector3(-4.25f, .65f, 0f), 90f);
            Place(mountain, "SafetyRail", new Vector3(4.25f, .65f, 0f), 90f);
            Place(mountain, "SafetyRail", new Vector3(-4.25f, .65f, 5f), 90f);
            Place(mountain, "SafetyRail", new Vector3(4.25f, .65f, 5f), 90f);
            Place(mountain, "SafetyRail", new Vector3(-4.25f, .65f, 10f), 90f);
            Place(mountain, "SafetyRail", new Vector3(4.25f, .65f, 10f), 90f);

            var tunnel = section.scenery[2].transform;
            ClearScenery(tunnel);
            Place(tunnel, "ModularTunnel", Vector3.zero);
            Place(tunnel, "DirtyTunnel", new Vector3(-8f, 0f, 0f), 0f, Vector3.one * .35f);
            Place(tunnel, "DirtyTunnel", new Vector3(8f, 0f, 0f), 0f, Vector3.one * .35f);
            Place(tunnel, "AsiaBuildings", new Vector3(-14f, 0f, 0f), 0f, Vector3.one * .3f);
            Place(tunnel, "AsiaBuildings", new Vector3(14f, 0f, 0f), 0f, Vector3.one * .3f);
            Place(tunnel, "StreetLamp", new Vector3(-5f, 0f, -10f), 90f, Vector3.one * .55f);
            Place(tunnel, "StreetLamp", new Vector3(5f, 0f, 10f), -90f, Vector3.one * .55f);
        }

        static void PatchPrefabs()
        {
            foreach (string name in new[] { "Tsila", "Officer", "RoadSection", "Barrier", "Tower", "Overhead", "Coin", "CoinMagnet", "SpeedBoost" })
            {
                string path = MobilePrototypeBuilder.Root + "/Prefabs/" + name + ".prefab";
                var root = PrefabUtility.LoadPrefabContents(path);
                try
                {
                    if (name == "Tsila") ReplacePlayer(root.GetComponent<RunnerPlayer>());
                    else if (name == "Officer") { ClearChildren(root.transform); MethodVisualBuilder.Character(root.transform, name).alwaysRun = true; }
                    else if (name == "RoadSection") PatchRoad(root);
                    else { ClearChildren(root.transform); MethodVisualBuilder.Model(root.transform, name); }
                    PrefabUtility.SaveAsPrefabAsset(root, path);
                }
                finally { PrefabUtility.UnloadPrefabContents(root); }
            }
        }

        static void PatchScene()
        {
            var scene = EditorSceneManager.OpenScene(MobilePrototypeBuilder.ScenePath);
            var game = Object.FindAnyObjectByType<RunnerGame>();
            // Replace explicitly because the saved scene contains serialized avatar overrides.
            var avatar = ReplacePlayer(game.player); avatar.game = game;
            var officerRoot = scene.GetRootGameObjects().Single(o => o.name == "Officer");
            ClearChildren(officerRoot.transform);
            var officer = MethodVisualBuilder.Character(officerRoot.transform, "Officer");
            officer.game = game; officer.alwaysRun = true; game.chase.officer = officer;
            officer.gameObject.SetActive(false);
            game.world.roadPrefab = AssetDatabase.LoadAssetAtPath<GameObject>(MobilePrototypeBuilder.Root + "/Prefabs/RoadSection.prefab");
            for (int i = 0; i < RunnerRules.ItemKindCount; i++)
                game.world.itemPrefabs[i] = AssetDatabase.LoadAssetAtPath<GameObject>(MobilePrototypeBuilder.Root + "/Prefabs/" + (RunnerItemKind)i + ".prefab").GetComponent<RunnerItem>();
            var preview = Object.FindAnyObjectByType<EditorPreview>();
            if (preview != null)
            {
                foreach (Transform tile in preview.transform.Cast<Transform>().ToArray()) Object.DestroyImmediate(tile.gameObject);
                for (int i = 0; i < RunnerRules.RoadCount; i++)
                {
                    var tile = (GameObject)PrefabUtility.InstantiatePrefab(game.world.roadPrefab, preview.transform);
                    tile.transform.localPosition = new Vector3(0f, 0f, (i - 1) * RunnerRules.RoadLength);
                }
            }
            PrefabUtility.RecordPrefabInstancePropertyModifications(game.player);
            PrefabUtility.RecordPrefabInstancePropertyModifications(game.world);
            EditorSceneManager.MarkSceneDirty(scene); EditorSceneManager.SaveScene(scene);
        }

        public static void ValidateAssets()
        {
            foreach (string name in Characters)
            {
                var instance = Object.Instantiate(AssetDatabase.LoadAssetAtPath<GameObject>(PrefabPath(name)));
                try
                {
                    var animator = instance.GetComponent<Animator>();
                    if (!animator.avatar.isValid || animator.runtimeAnimatorController.animationClips.Length != 4) throw new InvalidDataException("Invalid Meshy animator: " + name);
                    foreach (var skin in instance.GetComponentsInChildren<SkinnedMeshRenderer>())
                    {
                        if (skin.bones.Any(b => b == null) || skin.sharedMaterials.Any(m => m == null || m.GetTexture("_BaseMap") == null)) throw new InvalidDataException("Missing Meshy bones/textures: " + name);
                        foreach (var weight in skin.sharedMesh.boneWeights)
                            if (Mathf.Abs(weight.weight0 + weight.weight1 + weight.weight2 + weight.weight3 - 1f) > .003f) throw new InvalidDataException("Invalid Meshy weights");
                    }
                    animator.runtimeAnimatorController.animationClips.Single(c => c.name.EndsWith("_Slide")).SampleAnimation(instance, .5f);
                    var bounds = BlenderPackIntegration.SkinnedBounds(instance, instance.GetComponentInChildren<SkinnedMeshRenderer>());
                    Debug.Log("MESHY_SLIDE_BOUNDS " + name + " " + bounds);
                    if (bounds.min.y < -.03f || bounds.max.y > RunnerRules.SlideHeight + .03f) throw new InvalidDataException("Slide clearance failed: " + name);
                }
                finally { Object.DestroyImmediate(instance); }
            }
            var road = AssetDatabase.LoadAssetAtPath<GameObject>(PrefabPath("RoadSection"));
            var roadBounds = BlenderPackIntegration.VisualBounds(road);
            if (Mathf.Abs(roadBounds.size.z - 24f) > .01f) throw new InvalidDataException("Road module length failed");
            Debug.Log("TSILA_MESHY_VALIDATION_OK");
        }
    }
}
