using System;
using System.IO;
using System.Linq;
using UnityEditor;
using UnityEditor.Animations;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.Rendering;
using Object = UnityEngine.Object;

namespace TsilaRun.Editor
{
    // Prepared FBXs are generated by Tools/prepare_meshy.py from untouched GLB originals.
    public static class MeshyPackIntegration
    {
        public const string Root = "Assets/TsilaRun/Art/Meshy";
        public const string Source = Root + "/Source";
        public const string Generated = Root + "/Generated";
        static readonly string[] Characters = { "Tsila", "Officer", "HorrorGirl", "HorrorSkunx" };
        static readonly string[] Props =
        {
            "RoadSection", "Curb", "Tower", "Overhead", "Coin", "CoinMagnet", "Tree", "Palm", "House", "Building",
            "AsiaBuildings", "BaileyBridge", "SandFootprints", "Cliffs", "DirtyTunnel", "JungleHouse", "StreetLamp",
            "SidewalkCurbKit", "ModularTunnel", "OakTree", "RoadSectionAlt", "Rock", "RockTerrain", "SafetyRail",
            "SpeedBoost", "Barrier", "TropicalTreePack", "TropicalHouse"
        };
        public static string PrefabPath(string name) => Generated + "/" + name + ".prefab";

        [MenuItem("Tools/Tsila Run/Apply Meshy Art Pack")]
        public static void ApplyMenu()
        {
            if (EditorApplication.isPlayingOrWillChangePlaymode) return;
            if (!EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo()) return;
            ApplyBatch();
        }

        public static void ApplyAndCapture()
        {
            ApplyBatch();
            PrototypeScreenshots.CaptureBatch();
        }

        public static void ApplyBatch()
        {
            string backup = "Logs/MeshyBackup-" + DateTime.Now.ToString("yyyyMMdd-HHmmss");
            Directory.CreateDirectory(backup);
            foreach (string path in Directory.GetFiles(MobilePrototypeBuilder.Root + "/Prefabs"))
                File.Copy(path, backup + "/" + Path.GetFileName(path), true);
            File.Copy(MobilePrototypeBuilder.ScenePath, backup + "/TsilaRun.unity");
            Directory.CreateDirectory(Generated + "/Materials");
            AssetDatabase.Refresh(ImportAssetOptions.ForceSynchronousImport);
            foreach (string path in Directory.GetFiles(Source + "/Textures", "*.png"))
            {
                var importer = (TextureImporter)AssetImporter.GetAtPath(path.Replace('\\', '/'));
                bool normal = path.Contains("_Normal");
                importer.textureType = normal ? TextureImporterType.NormalMap : TextureImporterType.Default;
                importer.sRGBTexture = !normal;
                importer.mipmapEnabled = true;
                importer.maxTextureSize = path.Contains("BaseColor") && (path.Contains("Tsila_") || path.Contains("Officer_")) ? 2048 : 1024;
                importer.textureCompression = TextureImporterCompression.Compressed;
                importer.wrapMode = TextureWrapMode.Repeat;
                importer.SaveAndReimport();
            }
            foreach (string name in Characters)
            {
                ConfigureModel(name, true);
                ConfigureModel(name + "_LOD1", true);
                BuildCharacter(name);
                if (name.StartsWith("Horror")) HorrorContentBuilder.GroundNpcAnimation(name);
            }
            foreach (string name in Props)
            {
                ConfigureModel(name, false);
                BuildProp(name);
            }
            CharacterMotionBuilder.Build();
            PatchPrefabs();
            PatchScene();
            AssetDatabase.SaveAssets();
            ValidateAssets();
            Debug.Log("TSILA_MESHY_INTEGRATION_OK backup=" + backup);
        }

        public static void ConfigureModel(string name, bool character)
        {
            string path = Source + "/" + name + ".fbx";
            var importer = (ModelImporter)AssetImporter.GetAtPath(path);
            if (importer == null) throw new InvalidDataException("Missing prepared FBX: " + path);
            importer.globalScale = 1;
            importer.useFileUnits = true;
            importer.importCameras = false;
            importer.importLights = false;
            importer.isReadable = true;
            importer.importNormals = ModelImporterNormals.Import;
            importer.importTangents = ModelImporterTangents.CalculateMikk;
            importer.materialImportMode = ModelImporterMaterialImportMode.ImportStandard;
            importer.animationType = character ? ModelImporterAnimationType.Generic : ModelImporterAnimationType.None;
            importer.avatarSetup = character ? ModelImporterAvatarSetup.CreateFromThisModel : ModelImporterAvatarSetup.NoAvatar;
            importer.optimizeGameObjects = false;
            importer.importAnimation = character && !name.EndsWith("_LOD1");
            importer.animationCompression = ModelImporterAnimationCompression.Off;
            if (importer.importAnimation) importer.clipAnimations = Array.Empty<ModelImporterClipAnimation>();
            importer.SaveAndReimport();
            if (importer.importAnimation)
            {
                var clips = importer.defaultClipAnimations;
                foreach (var clip in clips)
                {
                    string state = name.StartsWith("Horror") ? "Run" : new[] { "Idle", "Run", "Jump", "Slide" }.FirstOrDefault(s => clip.name.EndsWith(s, StringComparison.OrdinalIgnoreCase));
                    if (state == null) throw new InvalidDataException("Unexpected Meshy clip: " + clip.name);
                    clip.name = state;
                    clip.loopTime = state == "Idle" || state == "Run";
                    clip.lockRootRotation = true;
                    clip.lockRootHeightY = true;
                    clip.lockRootPositionXZ = true;
                    clip.keepOriginalPositionY = true;
                    clip.keepOriginalPositionXZ = true;
                    clip.keepOriginalOrientation = true;
                }
                importer.clipAnimations = clips;
                importer.SaveAndReimport();
            }
            var model = AssetDatabase.LoadAssetAtPath<GameObject>(path);
            string assetName = name.Replace("_LOD1", "");
            foreach (var source in model.GetComponentsInChildren<Renderer>(true).SelectMany(r => r.sharedMaterials).Distinct())
            {
                if (source == null) throw new InvalidDataException("Missing material: " + name);
                string key = assetName + (character ? source.name.Contains("Body") ? "_Body" : "_FaceDetails" : "_Material");
                string matPath = Generated + "/Materials/" + key + ".mat";
                var shader = Shader.Find("Universal Render Pipeline/Lit");
                var mat = AssetDatabase.LoadAssetAtPath<Material>(matPath);
                if (mat == null) { mat = new Material(shader); AssetDatabase.CreateAsset(mat, matPath); }
                mat.shader = shader;
                mat.SetColor("_BaseColor", Color.white);
                mat.SetTexture("_BaseMap", AssetDatabase.LoadAssetAtPath<Texture2D>(Source + "/Textures/" + assetName + "_BaseColor.png"));
                var normal = AssetDatabase.LoadAssetAtPath<Texture2D>(Source + "/Textures/" + assetName + "_Normal.png");
                mat.SetTexture("_BumpMap", normal);
                // Use the mesh normals for the mobile material; keep baked maps available for later tuning.
                mat.DisableKeyword("_NORMALMAP");
                mat.SetFloat("_Smoothness", .12f);
                mat.SetFloat("_Cull", assetName == "Tree" || assetName == "Palm" ? 0f : 2f);
                mat.SetFloat("_Metallic", assetName == "Coin" ? .45f : 0f);
                if (assetName == "SandFootprints")
                {
                    mat.SetFloat("_Surface", 1f);
                    mat.SetFloat("_Blend", 0f);
                    mat.SetFloat("_SrcBlend", (float)BlendMode.SrcAlpha);
                    mat.SetFloat("_DstBlend", (float)BlendMode.OneMinusSrcAlpha);
                    mat.SetFloat("_ZWrite", 0f);
                    mat.SetOverrideTag("RenderType", "Transparent");
                    mat.EnableKeyword("_SURFACE_TYPE_TRANSPARENT");
                    mat.renderQueue = (int)RenderQueue.Transparent;
                }
                mat.enableInstancing = true;
                EditorUtility.SetDirty(mat);
                importer.AddRemap(new AssetImporter.SourceAssetIdentifier(typeof(Material), source.name), mat);
            }
            importer.SaveAndReimport();
        }

        static GameObject InstantiateModel(string name)
        {
            var model = Object.Instantiate(AssetDatabase.LoadAssetAtPath<GameObject>(Source + "/" + name + ".fbx"));
            model.name = name;
            foreach (var renderer in model.GetComponentsInChildren<Renderer>(true))
            {
                string assetName = name.Replace("_LOD1", "");
                renderer.sharedMaterials = renderer.sharedMaterials.Select(source =>
                {
                    string suffix = Characters.Contains(assetName) ? source.name.Contains("Body") ? "_Body" : "_FaceDetails" : "_Material";
                    var material = AssetDatabase.LoadAssetAtPath<Material>(Generated + "/Materials/" + assetName + suffix + ".mat");
                    if (material == null) throw new InvalidDataException("Missing mobile material for " + name);
                    return material;
                }).ToArray();
                renderer.shadowCastingMode = ShadowCastingMode.Off;
                renderer.receiveShadows = false;
                renderer.lightProbeUsage = LightProbeUsage.Off;
                renderer.reflectionProbeUsage = ReflectionProbeUsage.Off;
            }
            return model;
        }

        public static void BuildCharacter(string name)
        {
            var model = InstantiateModel(name);
            var low = InstantiateModel(name + "_LOD1");
            try
            {
                var animator = model.GetComponent<Animator>();
                if (animator == null || animator.avatar == null || !animator.avatar.isValid)
                    throw new InvalidDataException("Invalid character skeleton: " + name);
                string path = Generated + "/" + name + ".controller";
                var controller = AssetDatabase.LoadAssetAtPath<AnimatorController>(path);
                if (controller == null) controller = AnimatorController.CreateAnimatorControllerAtPath(path);
                var machine = controller.layers[0].stateMachine;
                foreach (var state in machine.states) machine.RemoveState(state.state);
                var imported = AssetDatabase.LoadAllAssetsAtPath(Source + "/" + name + ".fbx").OfType<AnimationClip>().Where(c => !c.name.StartsWith("__")).ToArray();
                foreach (string state in name.StartsWith("Horror") ? new[] { "Idle", "Run" } : new[] { "Idle", "Run", "Jump", "Slide" })
                {
                    var clip = Object.Instantiate(imported.Single(c => c.name == (name.StartsWith("Horror") ? "Run" : state)));
                    clip.name = name + "_" + state;
                    string clipPath = Generated + "/" + clip.name + ".anim";
                    var saved = AssetDatabase.LoadAssetAtPath<AnimationClip>(clipPath);
                    if (saved == null) { AssetDatabase.CreateAsset(clip, clipPath); saved = clip; }
                    else { EditorUtility.CopySerialized(clip, saved); Object.DestroyImmediate(clip); EditorUtility.SetDirty(saved); }
                    var entry = machine.AddState(state); entry.motion = saved;
                    if (state == "Idle") machine.defaultState = entry;
                }
                EditorUtility.SetDirty(controller);
                animator.runtimeAnimatorController = controller;
                animator.applyRootMotion = false;
                animator.cullingMode = AnimatorCullingMode.CullUpdateTransforms;
                var highSkin = model.GetComponentInChildren<SkinnedMeshRenderer>();
                var lowSkin = low.GetComponentInChildren<SkinnedMeshRenderer>();
                var bones = model.GetComponentsInChildren<Transform>().ToDictionary(t => t.name);
                lowSkin.bones = lowSkin.bones.Select(b => bones[b.name]).ToArray();
                lowSkin.rootBone = bones[lowSkin.rootBone.name];
                lowSkin.transform.SetParent(model.transform, true);
                lowSkin.name = name + "_GameplayLOD";
                foreach (var skin in new[] { highSkin, lowSkin })
                {
                    skin.quality = SkinQuality.Bone4;
                    skin.updateWhenOffscreen = false;
                    skin.localBounds = new Bounds(new Vector3(0f, .9f, 0f), new Vector3(4f, 4f, 5f));
                }
                var group = model.AddComponent<LODGroup>();
                group.SetLODs(new[] { new LOD(.25f, new Renderer[] { highSkin }), new LOD(.008f, new Renderer[] { lowSkin }) });
                group.localReferencePoint = Vector3.up * .9f; group.size = 1.8f;
                PrefabUtility.SaveAsPrefabAsset(model, PrefabPath(name));
            }
            finally { Object.DestroyImmediate(model); Object.DestroyImmediate(low); }
        }

        [Serializable] sealed class BoundsEntry { public string name; public float[] boundsMin, boundsMax; }
        [Serializable] sealed class BoundsManifest { public BoundsEntry[] models; }

        public static void BuildPropsBatch() { foreach (string name in Props) BuildProp(name); AssetDatabase.SaveAssets(); }

        static void BuildProp(string name)
        {
            var root = new GameObject(name);
            try
            {
                // Normalize in parent axes; imported meshes may retain rotated FBX roots.
                var high = new GameObject("High"); high.transform.SetParent(root.transform, false);
                InstantiateModel(name).transform.SetParent(high.transform, false);
                var low = new GameObject("Low"); low.transform.SetParent(root.transform, false);
                InstantiateModel(name + "_LOD1").transform.SetParent(low.transform, false);
                var manifest = JsonUtility.FromJson<BoundsManifest>("{\"models\":" + File.ReadAllText(Root + "/Manifest.json") + "}");
                var entry = manifest.models.Single(e => e.name == name);
                Vector3 expected = new Vector3(entry.boundsMax[0] - entry.boundsMin[0], entry.boundsMax[2] - entry.boundsMin[2], entry.boundsMax[1] - entry.boundsMin[1]);
                foreach (var visual in new[] { high, low })
                {
                    var measured = PlacedBounds(visual);
                    visual.transform.localScale = Vector3.Scale(visual.transform.localScale, new Vector3(expected.x / measured.size.x, expected.y / measured.size.y, expected.z / measured.size.z));
                    measured = PlacedBounds(visual);
                    visual.transform.localPosition -= new Vector3(measured.center.x, measured.min.y - entry.boundsMin[2], measured.center.z);
                }
                if (name == "Coin" || name == "CoinMagnet")
                {
                    Vector3 offset = Vector3.up * (.9f - PlacedBounds(high).center.y);
                    high.transform.localPosition += offset;
                    low.transform.localPosition += Vector3.up * (.9f - PlacedBounds(low).center.y);
                }
                if (name == "Overhead")
                {
                    foreach (var visual in new[] { high, low })
                        foreach (var filter in visual.GetComponentsInChildren<MeshFilter>())
                        {
                            var mesh = Object.Instantiate(filter.sharedMesh);
                            var vertices = mesh.vertices;
                            for (int i = 0; i < vertices.Length; i++)
                            {
                                Vector3 point = root.transform.InverseTransformPoint(filter.transform.TransformPoint(vertices[i]));
                                point.y = point.y <= 1f ? point.y * RunnerRules.OverheadClearance : point.y + RunnerRules.OverheadClearance - 1f;
                                vertices[i] = filter.transform.InverseTransformPoint(root.transform.TransformPoint(point));
                            }
                            mesh.vertices = vertices; mesh.RecalculateBounds(); mesh.RecalculateNormals();
                            string meshPath = Generated + "/Overhead" + (visual == high ? " High" : " Low") + ".asset";
                            var saved = AssetDatabase.LoadAssetAtPath<Mesh>(meshPath);
                            if (saved == null) { AssetDatabase.CreateAsset(mesh, meshPath); saved = mesh; }
                            else { EditorUtility.CopySerialized(mesh, saved); Object.DestroyImmediate(mesh); EditorUtility.SetDirty(saved); }
                            filter.sharedMesh = saved;
                        }
                }
                var group = root.AddComponent<LODGroup>();
                group.SetLODs(new[]
                {
                    new LOD(.12f, high.GetComponentsInChildren<Renderer>()),
                    new LOD(.01f, low.GetComponentsInChildren<Renderer>())
                });
                group.RecalculateBounds();
                PrefabUtility.SaveAsPrefabAsset(root, PrefabPath(name));
            }
            finally { Object.DestroyImmediate(root); }
        }

        static void ClearChildren(Transform parent)
        { foreach (Transform child in parent.Cast<Transform>().ToArray()) Object.DestroyImmediate(child.gameObject); }

        static RunnerAvatar ReplacePlayer(RunnerPlayer player)
        {
            ClearChildren(player.visual);
            var avatar = MethodVisualBuilder.Character(player.visual, "Tsila");
            avatar.player = player;
            player.rig = avatar.GetComponent<RunnerCharacterRig>();
            player.animatedSlide = true;
            return avatar;
        }

        static void Place(Transform parent, string asset, Vector3 position, float yaw = 0, Vector3 scale = default)
        {
            var model = MethodVisualBuilder.Model(parent, asset);
            model.name = asset == "RoadSection" ? asset : "Meshy " + asset;
            model.transform.localPosition = position;
            model.transform.localRotation = Quaternion.Euler(0, yaw, 0);
            if (scale.sqrMagnitude > 0f) model.transform.localScale = scale;
            if (asset != "RoadSection" && asset != "Curb")
                model.transform.localPosition += Vector3.up * (-.015f - PlacedBounds(model).min.y);
        }

        static void ClearScenery(Transform root, string preserve = null)
        {
            foreach (Transform child in root.Cast<Transform>().ToArray())
                if (child.name != preserve) Object.DestroyImmediate(child.gameObject);
        }

        static void PatchRoad(GameObject root)
        {
            var section = root.GetComponent<RunnerRoadSection>();
            foreach (Transform child in root.transform.Cast<Transform>().ToArray())
                if (child.GetComponent<RunnerRoadSection>() == null && !section.scenery.Contains(child.gameObject)) Object.DestroyImmediate(child.gameObject);
            Place(root.transform, "RoadSection", Vector3.zero);
            // The supplied mesh ends include curbs; a backing surface closes
            // small asphalt gaps between modules without covering the road art.
            MobilePrototypeBuilder.Shape(root.transform, "Road Foundation", PrimitiveType.Cube,
                new Vector3(0f, -.025f, 0f), new Vector3(8f, .04f, RunnerRules.RoadLength),
                AssetDatabase.LoadAssetAtPath<Material>(MobilePrototypeBuilder.Root + "/Materials/Road.mat"));
            foreach (int side in new[] { -1, 1 }) Place(root.transform, "Curb", new Vector3(side * 4.1f, -.05f, 0f));
            var island = section.scenery[0].transform;
            ClearScenery(island, "Island");
            var ground = island.Find("Island");
            if (ground != null)
            {
                ground.localPosition = new Vector3(0f, -.135f, 0f);
                ground.localScale = new Vector3(64f, .25f, 24f);
                ground.GetComponent<Renderer>().sharedMaterial = MenuPolishBuilder.SandMaterial();
            }
            Place(island, "Palm", new Vector3(-7.5f, 0f, 7f), -12f);
            Place(island, "Tree", new Vector3(9.5f, 0f, -5f));
            Place(island, "TropicalHouse", new Vector3(-13f, 0f, 0f), 90f);
            Place(island, "Building", new Vector3(21f, 0f, 4f), -90f);
            foreach (Transform prop in island)
            {
                if (prop.name == "Island") continue;
                var spacing = prop.gameObject.AddComponent<ScenerySpacing>();
                spacing.period = prop.name.Contains("Building") ? 5 : 3;
                spacing.slot = prop.name.Contains("Palm") ? 0 : prop.name.Contains("Tree") ? 1 : prop.name.Contains("Building") ? 3 : 2;
            }
            ClearRoadEnvelope(island);
            var mountain = section.scenery[1].transform;
            ClearScenery(mountain);
            MobilePrototypeBuilder.Shape(mountain, "Mountain Sand", PrimitiveType.Cube,
                new Vector3(0f, -.135f, 0f), new Vector3(96f, .25f, RunnerRules.RoadLength), MenuPolishBuilder.SandMaterial());
            foreach (int side in new[] { -1, 1 })
            {
                Place(mountain, "Cliffs", new Vector3(side * 22f, -2f, 0f));
                Place(mountain, "RockTerrain", new Vector3(side * 26f, -3f, 0f));
                Place(mountain, "Rock", new Vector3(side * 8f, 0f, side * 8f), side * 20f, Vector3.one * .65f);
                Place(mountain, "Tree", new Vector3(side * 13f, 0f, -side * 6f));
            }
            foreach (Transform prop in mountain)
                if (prop.name.Contains("Rock") || prop.name.Contains("Tree"))
                {
                    var spacing = prop.gameObject.AddComponent<ScenerySpacing>(); spacing.period = 3;
                    spacing.slot = prop.localPosition.x < 0 ? 0 : 2;
                }
            ClearRoadEnvelope(mountain);
            var tunnel = section.scenery[2].transform;
            ClearScenery(tunnel);
            var wallMaterial = AssetDatabase.LoadAssetAtPath<Material>(MobilePrototypeBuilder.Root + "/Materials/Ink.mat");
            var lightMaterial = AssetDatabase.LoadAssetAtPath<Material>(MobilePrototypeBuilder.Root + "/Materials/Cream.mat");
            foreach (int side in new[] { -1, 1 })
            {
                MobilePrototypeBuilder.Shape(tunnel, "Tunnel Wall", PrimitiveType.Cube, new Vector3(side * 5f, 4.5f, 0), new Vector3(1, 9, 24), wallMaterial);
                MobilePrototypeBuilder.Shape(tunnel, "Tunnel Light", PrimitiveType.Cube, new Vector3(side * 4.45f, 2.8f, 0), new Vector3(.06f, .12f, 6), lightMaterial);
            }
            MobilePrototypeBuilder.Shape(tunnel, "Tunnel Ceiling", PrimitiveType.Cube, new Vector3(0, 9f, 0), new Vector3(11, .4f, 24), wallMaterial);
            // Collections of disconnected kit parts stay available in Art, away from the playable road.
        }

        public static Bounds PlacedBounds(GameObject visual)
        {
            bool first = true; Bounds result = default;
            Transform parent = visual.transform.parent;
            foreach (var filter in visual.GetComponentsInChildren<MeshFilter>(true))
                foreach (var vertex in filter.sharedMesh.vertices)
                {
                    Vector3 point = filter.transform.TransformPoint(vertex);
                    if (parent != null) point = parent.InverseTransformPoint(point);
                    if (first) { result = new Bounds(point, Vector3.zero); first = false; } else result.Encapsulate(point);
                }
            return result;
        }

        static void ClearRoadEnvelope(Transform scenery)
        {
            foreach (Transform prop in scenery)
            {
                if (prop.name == "Island" || prop.name == "Mountain Sand") continue;
                var bounds = PlacedBounds(prop.gameObject);
                float shift = prop.localPosition.x < 0f ? Mathf.Min(0, -4.3f - bounds.max.x) : Mathf.Max(0, 4.3f - bounds.min.x);
                prop.localPosition += Vector3.right * shift;
            }
        }

        public static void RefreshLayoutBatch()
        {
            PatchPrefabs(); PatchScene(); AssetDatabase.SaveAssets();
        }

        static void PatchPrefabs()
        {
            foreach (string name in new[] { "Tsila", "Officer", "RoadSection", "Barrier", "Tower", "Overhead", "Coin", "CoinMagnet", "SpeedBoost" })
            {
                string path = MobilePrototypeBuilder.Root + "/Prefabs/" + name + ".prefab";
                var root = PrefabUtility.LoadPrefabContents(path);
                try
                {
                    if (name == "Tsila") ReplacePlayer(root.GetComponent<RunnerPlayer>());
                    else if (name == "Officer") { ClearChildren(root.transform); MethodVisualBuilder.Character(root.transform, name).alwaysRun = true; }
                    else if (name == "RoadSection") PatchRoad(root);
                    else
                    {
                        ClearChildren(root.transform); MethodVisualBuilder.Model(root.transform, name);
                        if (name == "Overhead")
                        {
                            var box = root.GetComponent<RunnerItem>().hitbox;
                            box.center = new Vector3(0f, RunnerRules.OverheadClearance + box.size.y * .5f, 0f);
                        }
                    }
                    PrefabUtility.SaveAsPrefabAsset(root, path);
                }
                finally { PrefabUtility.UnloadPrefabContents(root); }
            }
        }

        static void PatchScene()
        {
            var scene = EditorSceneManager.OpenScene(MobilePrototypeBuilder.ScenePath);
            var game = Object.FindAnyObjectByType<RunnerGame>();
            if (PrefabUtility.IsPartOfPrefabInstance(game.player))
                PrefabUtility.UnpackPrefabInstance(PrefabUtility.GetOutermostPrefabInstanceRoot(game.player), PrefabUnpackMode.Completely, InteractionMode.AutomatedAction);
            // Replace explicitly because the saved scene contains serialized avatar overrides.
            var avatar = ReplacePlayer(game.player); avatar.game = game;
            var officerRoot = scene.GetRootGameObjects().Single(o => o.name == "Officer");
            if (PrefabUtility.IsPartOfPrefabInstance(officerRoot))
                PrefabUtility.UnpackPrefabInstance(PrefabUtility.GetOutermostPrefabInstanceRoot(officerRoot), PrefabUnpackMode.Completely, InteractionMode.AutomatedAction);
            ClearChildren(officerRoot.transform);
            var officer = MethodVisualBuilder.Character(officerRoot.transform, "Officer");
            officer.game = game; officer.alwaysRun = true; game.chase.officer = officer;
            officer.gameObject.SetActive(false);
            game.world.roadPrefab = AssetDatabase.LoadAssetAtPath<GameObject>(MobilePrototypeBuilder.Root + "/Prefabs/RoadSection.prefab");
            for (int i = 0; i < RunnerRules.ItemKindCount; i++)
                game.world.itemPrefabs[i] = AssetDatabase.LoadAssetAtPath<GameObject>(MobilePrototypeBuilder.Root + "/Prefabs/" + (RunnerItemKind)i + ".prefab").GetComponent<RunnerItem>();
            var preview = Object.FindAnyObjectByType<EditorPreview>();
            if (preview != null)
            {
                foreach (Transform tile in preview.transform.Cast<Transform>().ToArray()) Object.DestroyImmediate(tile.gameObject);
                for (int i = 0; i < RunnerRules.RoadCount; i++)
                {
                    var tile = (GameObject)PrefabUtility.InstantiatePrefab(game.world.roadPrefab, preview.transform);
                    tile.transform.localPosition = new Vector3(0f, 0f, (i - 1) * RunnerRules.RoadLength);
                }
            }
            if (PrefabUtility.IsPartOfPrefabInstance(game.player)) PrefabUtility.RecordPrefabInstancePropertyModifications(game.player);
            if (PrefabUtility.IsPartOfPrefabInstance(game.world)) PrefabUtility.RecordPrefabInstancePropertyModifications(game.world);
            HorrorContentBuilder.ApplyToScene(game);
            EditorSceneManager.MarkSceneDirty(scene); EditorSceneManager.SaveScene(scene);
        }

        public static void ValidateAssets()
        {
            foreach (string name in Characters)
            {
                var instance = Object.Instantiate(AssetDatabase.LoadAssetAtPath<GameObject>(PrefabPath(name)));
                try
                {
                    var animator = instance.GetComponent<Animator>();
                    if (!animator.avatar.isValid || animator.runtimeAnimatorController.animationClips.Length != (name.StartsWith("Horror") ? 2 : 4)) throw new InvalidDataException("Invalid Meshy animator: " + name);
                    foreach (var skin in instance.GetComponentsInChildren<SkinnedMeshRenderer>())
                    {
                        if (skin.bones.Any(b => b == null) || skin.sharedMaterials.Any(m => m == null || m.GetTexture("_BaseMap") == null)) throw new InvalidDataException("Missing Meshy bones/textures: " + name);
                        foreach (var weight in skin.sharedMesh.boneWeights)
                            if (Mathf.Abs(weight.weight0 + weight.weight1 + weight.weight2 + weight.weight3 - 1f) > .003f) throw new InvalidDataException("Invalid Meshy weights");
                    }
                    if (name.StartsWith("Horror")) continue;
                    animator.runtimeAnimatorController.animationClips.Single(c => c.name.EndsWith("_Slide")).SampleAnimation(instance, .5f);
                    var bounds = BlenderPackIntegration.SkinnedBounds(instance, instance.GetComponentInChildren<SkinnedMeshRenderer>());
                    Debug.Log("MESHY_SLIDE_BOUNDS " + name + " " + bounds);
                    if (bounds.min.y < -.03f || bounds.max.y > RunnerRules.SlideHeight + .03f) throw new InvalidDataException("Slide clearance failed: " + name);
                }
                finally { Object.DestroyImmediate(instance); }
            }
            var road = AssetDatabase.LoadAssetAtPath<GameObject>(PrefabPath("RoadSection"));
            var roadBounds = BlenderPackIntegration.VisualBounds(road);
            if (Mathf.Abs(roadBounds.size.z - 24f) > .01f) throw new InvalidDataException("Road module length failed");
            Debug.Log("TSILA_MESHY_VALIDATION_OK");
        }
    }
}
